/**
 * Regenerates src/i18n/generated-route-locales.ts from live Medusa regions + store locales.
 * Requires NEXT_PUBLIC_MEDUSA_BACKEND_URL and NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY.
 */
import { writeFileSync } from "fs"
import { join } from "path"

import {
  computeAllowedRouteLocales,
  defaultLocaleTagForCountry,
} from "../src/lib/i18n/locale-policy"

const BACKEND = process.env.NEXT_PUBLIC_MEDUSA_BACKEND_URL
const KEY = process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
const DEFAULT_REGION = (process.env.NEXT_PUBLIC_DEFAULT_REGION || "us").toLowerCase()

console.log(BACKEND, KEY, DEFAULT_REGION)

async function main() {
  if (!BACKEND || !KEY) {
    console.error(
      "Missing NEXT_PUBLIC_MEDUSA_BACKEND_URL or NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY"
    )
    process.exit(1)
  }

  const headers = { "x-publishable-api-key": KEY }

  const [regionsRes, localesRes] = await Promise.all([
    fetch(`${BACKEND}/store/regions`, { headers }),
    fetch(`${BACKEND}/store/locales`, { headers }),
  ])

  if (!regionsRes.ok || !localesRes.ok) {
    console.error(
      "Failed to fetch regions or locales:",
      regionsRes.status,
      localesRes.status
    )
    process.exit(1)
  }

  const { regions } = (await regionsRes.json()) as {
    regions: { countries?: { iso_2?: string | null }[] }[]
  }
  const { locales } = (await localesRes.json()) as {
    locales: { code: string }[]
  }

  const list = locales ?? []
  const routeLocales = computeAllowedRouteLocales(regions ?? [], list)
  if (routeLocales.length === 0) {
    console.error("No route locales computed — check regions and locales in Admin.")
    process.exit(1)
  }

  let defaultLocale = defaultLocaleTagForCountry(DEFAULT_REGION, list)
  if (!routeLocales.includes(defaultLocale)) {
    defaultLocale = routeLocales[0]!
  }

  const content = `/* eslint-disable */
// AUTO-GENERATED by scripts/generate-route-locales.ts — do not edit by hand.
// Run: pnpm generate:locales (requires NEXT_PUBLIC_MEDUSA_BACKEND_URL + NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY)
export const routeLocales = ${JSON.stringify(routeLocales)} as const

export const defaultRouteLocale = ${JSON.stringify(defaultLocale)} as (typeof routeLocales)[number]
`

  const out = join(process.cwd(), "src/i18n/generated-route-locales.ts")
  writeFileSync(out, content, "utf8")
  console.log(`Wrote ${routeLocales.length} locales, default ${defaultLocale} → ${out}`)
}

main().catch(function onError(e) {
  console.error(e)
  process.exit(1)
})
