/* eslint-disable */
// AUTO-GENERATED by scripts/generate-route-locales.ts — do not edit by hand.
// Run: pnpm generate:locales (requires NEXT_PUBLIC_MEDUSA_BACKEND_URL + NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY)
export const routeLocales = [
  "ar-EG",
  "da-DK",
  "de-DE",
  "en-DE",
  "en-DK",
  "en-EG",
  "en-ES",
  "en-FR",
  "en-GB",
  "en-IT",
  "en-SE",
  "es-ES",
  "fr-FR",
  "it-IT",
  "sv-SE",
] as const

export const defaultRouteLocale = "ar-EG" as (typeof routeLocales)[number]
